Sintaraでメモアプリを作成しました
smallmonkeykey/sintara-webmemo pull request #1
Opened 2023-09-06 04:28 UTC by smallmonkeykey

ご確認よろしくお願いいたします。

2023-09-12 15:36 UTC, u1tnk requested changes
> レビュアーが、ローカルでアプリケーションを立ち上げるための手順書がREADMEに記載されていること

こちらの対応をお願いします。

2023-09-12 15:36 UTC, u1tnk commented on memos.json
> +[{"name":"メモ１","message":"メモ１の内容です","id":1}]
データファイルはコミットしないようにしましょう。
なので初期動作時はファイルは無い状態です。

2023-09-12 15:36 UTC, u1tnk commented on main.rb
> +  @memos_date = load_jsonfile
_dataや_infoはあまり意味が無いので無い方が良いですね。

参考: https://u1tnk.github.io/blog/2022/12/04/naming_variable/

2023-09-12 15:36 UTC, u1tnk commented on main.rb
> +    id_memo_data = memo_data if memo_data.value?(params[:id].to_i)
見つかった時点でreturnしてしまえば良いですね。

2023-09-12 15:36 UTC, u1tnk commented on main.rb
> +  id_memo_data = {}
前に id_と付いてる意図がちょっと分かりづらいですね。無くて大丈夫だと思います。
下のコメントでこの変数は不要になりますが、他でも同じ名前使ってるので。

2023-09-12 15:36 UTC, u1tnk commented on main.rb
> +  new_memo_id = give_number_to_memos_data(memos_data)
一箇所その直下でしか使わないのであれば変数に入れずにそのまま代入して良いですね。

2023-09-12 15:36 UTC, u1tnk commented on main.rb
> +  params['id'] = new_memo_id
paramsはsinatraという仕組みでcontroller内の入力値として扱われるので、ここには書きこまない方が良いです。
更にはparamsは何が入ってるか分からないのでこのまま保存するのは良くないです。
例えば curlコマンドなどで、 ここに直接リクエストして、意味の無いパラメータを追加するとそのままjsonに書きこまれてしまいます。
paramsはチェックするまで信用しないのは今後学習するセキュリティの観点からも大事です。

2023-09-12 15:36 UTC, u1tnk commented on memos.json
> +[{"name":"メモ１","message":"メモ１の内容です","id":1}]
このデータ形式はデータベースに近く、そのままでも問題は無いですが、jsonなのでidをkeyにするという方法もあります。
どっちでも良いので参考まで。

2023-09-12 15:36 UTC, u1tnk commented on main.rb
> +  arry_number = 0
まず、 arrayを短縮するなら aryとかでしょうか。ちょっと中途半端だし、基本的には悩むなら省略しない方が良いです。

参考: [プログラミング初心者は変数名やメソッド名を略さない方がいいよ、という話 - give IT a try](https://blog.jnito.com/entry/2020/10/20/092724)

また、自分で iを作らなくても大丈夫です。 Enumerable あたりのメソッドを探してみてください。

2023-09-12 15:36 UTC, u1tnk commented on main.rb
> +  edit_memo_data = params.delete_if { |key, _value| key == '_method' }
edit_memo_data だとeditするメソッドに見えてしまいます。
`edited_memo_data`  などにすると変数だと分かりやすくなります。

2023-09-14 08:55 UTC, smallmonkeykey commented on main.rb
> +  @memos_date = load_jsonfile
"変数は全て情報だしデータなので、大体のパターンはinfo/dataを消しても大差ない"
読んだはずなのに、忘れてつけていました😭教えてくださり、ありがとうございます！
[3ca2f34](https://github.com/smallmonkeykey/sintara-webmemo/pull/1/commits/3ca2f343c99efedfa0d8e26d246645d6a1d8b1fb)

2023-09-15 00:31 UTC, smallmonkeykey commented on main.rb
> +    id_memo_data = memo_data if memo_data.value?(params[:id].to_i)
returnの使い方、あまり理解できていなかったのですが、今回のおかげで理解できたように思います。ありがとうございます！
[a6e31a9](https://github.com/smallmonkeykey/sintara-webmemo/pull/1/commits/a6e31a90ef57509c859ad5ad4df0fa133fb78585)

2023-09-15 00:34 UTC, smallmonkeykey commented on main.rb
> +  new_memo_id = give_number_to_memos_data(memos_data)
修正しました！
[d383a78](https://github.com/smallmonkeykey/sintara-webmemo/pull/1/commits/d383a78d9568ef2fe1fe7a67234627b5d770ecba)

2023-09-15 02:34 UTC, smallmonkeykey commented on main.rb
> +  edit_memo_data = params.delete_if { |key, _value| key == '_method' }
なるほど…！動詞から始めちゃうとメソッドにみえるんですね。
メソッド名: 動詞から始める
変数名:  名詞

2023-09-15 05:38 UTC, smallmonkeykey commented on main.rb
> +  params['id'] = new_memo_id
curlコマンドを試してみたら、入力されたくない値もいれることができました😭
paramsをそのまま代入する危険を知りました。ありがとうございます🙏
[08a047e](https://github.com/smallmonkeykey/sintara-webmemo/pull/1/commits/08a047efd90df016906c834a8c551c6248790af8)

2023-09-15 05:42 UTC, smallmonkeykey commented on main.rb
> +  arry_number = 0
find_indexを使いました！

arrayは、arryと完全につづりを間違って覚えていました😱気づかせてくださり、ありがとうございます！
[8bc4680](https://github.com/smallmonkeykey/sintara-webmemo/pull/1/commits/8bc4680d7b5635e5ea9a6494d8ec14763b41d2cf)

2023-09-15 05:48 UTC, smallmonkeykey commented on memos.json
> +[{"name":"メモ１","message":"メモ１の内容です","id":1}]
jsonなのでidをkeyにするという方法というのは、
```
{
  1: {
    "name": "taro"
  }
}
```
のような形式であっていますか？？

2023-09-15 08:01 UTC, u1tnk commented on memos.json
> +[{"name":"メモ１","message":"メモ１の内容です","id":1}]
はい、そうです！
jsonのような柔軟なデータフォーマットならこっちの方が使いやすいと思います。
先のDB利用版だと現在のフォーマットと同様なんですが、DBの方はSQLで一件取得するとか一件更新するとか簡単にできるんですよね。

2023-09-15 08:21 UTC, u1tnk requested changes

2023-09-15 08:21 UTC, u1tnk commented on memos.json
> +[]
前の指摘はデータを空にするのではなく、ファイル自体コミットしないということです。
データファイルはgit管理しない(そうしないとプログラムを動かすために statusで差分が出て大変)ようにしましょう。

2023-09-15 08:21 UTC, u1tnk commented on main.rb
> +  @id_memo_data = take_unique_memo(memos, params)
変数名指摘してたのに変わっていないようです… 🤔

2023-09-15 08:21 UTC, u1tnk commented on main.rb
> +def take_unique_memo(memos, params)
'take_unique_memo' この名前は分かりやすくてとても良いのですが、 `take_memo`でも通じそうだし、DB(というかRails)に慣れると慣習としては `find_memo` で十分となります。

慣習は慣れてくれば自然と使えるようになりますが、短い方でも伝わるなら短い方が読みやすいというところは意識した方が良いと思います。

修正するほどでは無いですが、考え方を補足しておきました。

2023-09-15 08:21 UTC, u1tnk commented on main.rb
> +  ids = memos.map { |memo_data| memo_data['id'] }
これは maxにブロックを渡せるのを知ってるともっと簡潔に書けそうですね。

2023-09-15 08:21 UTC, u1tnk commented on README.md
> +# 概要
👍

2023-09-15 08:21 UTC, u1tnk commented on README.md
> +2. sintara-webmemoのフォルダの中で、`git switch develop`をしてください
これはPRがマージされることを前提にしている(し、今後他のブランチを作るかもしれない)ので `git switch`は不要です。

2023-09-16 02:15 UTC, smallmonkeykey commented on main.rb
> +  @id_memo_data = take_unique_memo(memos, params)
見過ごしており、すいません🙇
修正しました！
[id_memo_dataをmemoに名前変更](https://github.com/smallmonkeykey/sintara-webmemo/pull/1/commits/bdefbf91a692ecc6a8dfff9ed138b1eb38df7195)

2023-09-16 06:13 UTC, smallmonkeykey commented on memos.json
> +[]
おお！なるほど…！確かに毎回差分がでて大変でした。理解がたりず、すいません🙇
memos.jsonを.gitignoreにいれました！

2023-09-16 08:08 UTC, smallmonkeykey commented on main.rb
> +  ids = memos.map { |memo_data| memo_data['id'] }
`memos.max {|a, b| a["id"] <=> b["id"] } ["id"].to_i + 1`
と書きたかったのですが、データファイルが空の時にハッシュがnilと返ってきてしまい、to_iができませんでした😭

簡潔に書けずにすいません。
ヒントなどがあればお願いいたします🙇‍♀️

[8e8a4f2](https://github.com/smallmonkeykey/sintara-webmemo/pull/1/commits/8e8a4f26d94a560e26a604792724a7b5b560d016)

2023-09-16 08:13 UTC, smallmonkeykey commented on README.md
> +2. sintara-webmemoのフォルダの中で、`git switch develop`をしてください
該当箇所を削除し、変更しました！

[eb247f6](https://github.com/smallmonkeykey/sintara-webmemo/pull/1/commits/eb247f6c8ea0dfda4bf1024f0792624c3f0e3566)

2023-09-16 13:20 UTC, u1tnk commented on main.rb
> +  ids = memos.map { |memo_data| memo_data['id'] }
すみません！

僕がちょっと勘違いしていて maxにブロック渡した方がややこしくなりますね 🙏 

`memos.map { |memo_data| memo_data['id'] }.max`

と繋げた方が見やすいというのと

`memos.map { _1['id'] }.max`

一行のブロックなら `_1` を遣った方がすっきりします。

あと、rubyは `nil.to_i`は0なので別の原因を勘違いされたのかと思います。

2023-09-16 13:25 UTC, u1tnk commented on main.rb
> +  ids = memos.map { |memo_data| memo_data['id'] }
今気づきましたが、僕が `max_by` と勘違いしてました… 🙈  
今のmax_byで大丈夫ですが、一行にはできますよ。

2023-09-16 13:43 UTC, u1tnk requested changes

2023-09-16 13:43 UTC, u1tnk commented on main.rb
> +  memos.each do |memo_data|
ここはdataを使わない意味でも railsなどの慣習的な意味でもブロック引数は `memo` で大丈夫です。
慣習的に 複数形をeachしたときのブロック引数は単数系にします。

2023-09-16 13:43 UTC, u1tnk commented on main.rb
> +  edited_memo_data = params.delete_if { |key, _value| key == '_method' }
ここらへんも dataいらないですね。

2023-09-16 13:43 UTC, u1tnk commented on main.rb
> +  edited_memo_data = params.delete_if { |key, _value| key == '_method' }
前にも触れましたが、paramsは編集してはダメです。
このpatchメソッドへの入力と思ってください。
また _methodはsinatraが入れてくれているものなので、もしこれを参照している他の処理があった場合原因不明の不具合となって危険です。

また、結局これもparamsをそのまま保存しているので、`_method`以外のパラメータが付けられると変な値が入ります。
ブラックリストではなく、ホワイトリストで必要な入力値のみを取得するようにしてください。

2023-09-16 13:43 UTC, u1tnk commented on main.rb
> +    memo_data.value?(params[:id].to_i)
https://docs.ruby-lang.org/ja/latest/method/Hash/i/has_value=3f.html
value?は `has_value?` と同じでちょっとわかりづらいので `has_value?` を使った方が良いかと思いましたが、
それ以前にちょっとおかしそうです。 `value?`は 一件のmemoのhashのどれか一つが idの値であれば良いので(実際は型が違うのでバグにはなりませんが)、全てのvalueと一致チェックするのはおかしいです。

2023-09-16 13:43 UTC, u1tnk commented on main.rb
> +  array_number = memos.find_index do |memo_data|
find_indexだし、変数名はindexで良いと思います。indexは配列の添え字を表すときによく使います。

2023-09-16 13:43 UTC, u1tnk commented on main.rb
> +    memo_data.value?(params[:id].to_i)
また、take_unique_memoとidを取得する部分かぶっていて、ちょっとだけ複雑なのでメソッドにした方が良いですね。

2023-09-16 13:43 UTC, u1tnk commented on main.rb
> +    JSON.load_file(file) || []
`memos.json` が存在しないときエラーになるはずなので対処が必要です。

2023-09-18 03:38 UTC, smallmonkeykey commented on main.rb
> +    JSON.load_file(file) || []
修正しました！
[ec99d70](https://github.com/smallmonkeykey/sintara-webmemo/pull/1/commits/ec99d70bfe870cc8ec6017451845eb030bb2610a)

2023-09-18 03:47 UTC, smallmonkeykey commented on main.rb
> +    memo_data.value?(params[:id].to_i)
教えていただいたparamsを直接編集しなかった結果、該当箇所が一行でかけたため、メソッドにはしておりません…🙇

[0a96899](https://github.com/smallmonkeykey/sintara-webmemo/pull/1/commits/0a968993ff9a11153f5282ef7cae18301d5e4351)

2023-09-18 03:50 UTC, smallmonkeykey commented on main.rb
> +  edited_memo_data = params.delete_if { |key, _value| key == '_method' }
paramsの件、教えていただいたのに自分で気づけずすいません🙇‍♀️
file changedでしっかり見直すことと、dataの変数名の件もですが、教えていただいたことを活かして他にも訂正箇所がないかどうか見ていきたいと思います。

2023-09-18 03:52 UTC, smallmonkeykey commented on main.rb
> +  array_number = memos.find_index do |memo_data|
教えてくださり、ありがとうございます！自分で言葉を作らずに、一般な言葉がないかを考えるのが大切だとわかりました。

2023-09-18 11:04 UTC, smallmonkeykey commented on main.rb
> +  ids = memos.map { |memo_data| memo_data['id'] }
番号指定パラメータ、チェリー本で出てきたはずなのに何かわからず調べてしまいました…！！
こんなにスッキリするんですね！教えてくださって、ありがとうございます！

あと、hashに対してmapををしてその結果をmaxメソッド使うと一番読みやすいし、理解しやすくてびっくりしました。こうすれば良いのかとめちゃくちゃ勉強になりました。ありがとうございます🙏

2023-09-18 15:57 UTC, u1tnk requested changes
もうちょいですね！

2023-09-18 15:57 UTC, u1tnk commented on main.rb
> +  unless FileTest.exist?('memos.json')
これは load_jsonfile内でやっているのでは？

2023-09-19 02:02 UTC, u1tnk commented on main.rb
> +    memo_data.value?(params[:id].to_i)
`memos.find_index { |memo| memo["id"] == edited_memo[:id] }`

これですね。一行で書けても、「これ何回も書くのいやだなあ 🤔」ってときはメソッドにすることもよくありますが、微妙なラインなのでヨシとします！

2023-09-19 02:03 UTC, u1tnk commented on main.rb
> +  edited_memo_data = params.delete_if { |key, _value| key == '_method' }
💪

2023-09-19 02:53 UTC, u1tnk commented on main.rb
> +  ids = memos.map { |memo_data| memo_data['id'] }
実際便利になるケースを見るとすっと入りますよね。
mapはめっちゃ便利なので、eachを使ったときはmap使えないか考えてみると良いです！

2023-09-19 03:23 UTC, smallmonkeykey commented on main.rb
> +  unless FileTest.exist?('memos.json')
git cloneした段階で、jsonファイルはないので、URLにアクセスした時につくられるようにしました。
それ以後は、アプリのコードを触ることはないと仮定して、アプリ内でメモの削除の操作を行った場合、jsonファイルの[]は消えないので、このようなコードにしました！

[c4e90d2](https://github.com/smallmonkeykey/sintara-webmemo/pull/1/commits/c4e90d215e47cf6515674854383be979ae35bdf0)

2023-09-19 16:39 UTC, u1tnk commented on main.rb
> +  unless FileTest.exist?('memos.json')
ちょっとソースの経緯が見えづらかったのですが、最終的な形が問題無かったのでヨシです！

2023-09-19 16:40 UTC, u1tnk requested changes

2023-09-19 16:40 UTC, u1tnk commented on main.rb
> +    File.open('memos.json', 'w') do |file|
ここで
`write_to_jsonfile([])`

とやってしまえば良さそう。

2023-09-19 16:40 UTC, u1tnk commented on main.rb
> +  File.open('memos.json', 'r') do |file|
今さらですが、 `memos.json`のファイル名を定数で定義して絶対にズレないようにすると安心ですね。

2023-09-21 04:45 UTC, smallmonkeykey commented on main.rb
> +    File.open('memos.json', 'w') do |file|
自分では全く気づきませんでした…！！スッキリして感動してます。教えてくださってありがとうございます！
[d98c7a5](https://github.com/smallmonkeykey/sintara-webmemo/pull/1/commits/d98c7a540a8d62dd4e5c35851e7bd390b5d6bd4f)

2023-09-21 04:47 UTC, smallmonkeykey commented on main.rb
> +  File.open('memos.json', 'r') do |file|
勝手に、定数は数字だけと思い込んで使っていませんでした😭
修正しました！

[7e9891a](https://github.com/smallmonkeykey/sintara-webmemo/pull/1/commits/7e9891a9aeca032d2809408e4058402957d8778f)

2023-09-21 04:49 UTC, smallmonkeykey commented on main.rb
> +  unless FileTest.exist?('memos.json')
経緯、わかりにくくててすいません🙇‍♀️
もっと早めに伝えておけばよかったです…。

2023-09-21 12:16 UTC, u1tnk approved these changes

2023-09-22 08:26 UTC, merged